In [1]:
import sys
import types
import numpy as np

# 1. CREATE THE PACKAGE STRUCTURE
# We create '_core' as a package and link the internal C-extensions
_core = types.ModuleType("numpy._core")
_core.__path__ = [] # This tells Python it's a package, not just a file

# # 2. MAP THE CRITICAL SUB-MODULES
# # These are the specific 'addresses' the pickle file is trying to visit
# sys.modules['numpy._core'] = _core
# sys.modules['numpy._core.numeric'] = np.core.numeric
# sys.modules['numpy._core.multiarray'] = np.core.multiarray
# sys.modules['numpy._core.umath'] = np.core.umath

# print("✅ Deep Bridge established. NumPy 1.x is now masking as a 2.x Package.")

# 3. NOW RUN THE LOAD
import pandas as pd
import pickle
import os

DATA_FOLDER = 'cytotoxicity_data'
files = ['HEK293_train_BM.pkl', 'HEK293_test_BM.pkl', 'tox21_all.pkl']

def peek_native_pickle(folder, file_name):
    file_path = os.path.join(folder, file_name)
    print(f"\n--- Checking {file_name} ---")
    
    if not os.path.exists(file_path):
        print("File not found.")
        return

    with open(file_path, 'rb') as f:
        # latin1 handles the byte-stream conversion of the NumPy arrays
        data = pickle.load(f, encoding='latin1')
        
    print(f"Type: {type(data)}")
    if isinstance(data, pd.DataFrame):
        print(f"Columns: {data.columns.tolist()}")
        display(data.head(3))
    elif isinstance(data, dict):
        print(f"Keys: {list(data.keys())}")
    else:
        print(f"Content: {str(data)[:200]}...")

for f in files:
    peek_native_pickle(DATA_FOLDER, f)

--- Checking HEK293_train_BM.pkl ---
Type: <class 'pandas.core.frame.DataFrame'>
Columns: ['SMILES', 'mol', 'Outcome', 'PUBCHEM_CID', 'cell_type', 'cluster_id', 'MorganFP', 'TB_Cluster', 'BM_Cluster', 'Fold']

,SMILES,mol,Outcome,PUBCHEM_CID,cell_type,cluster_id,MorganFP,TB_Cluster,BM_Cluster,Fold
0,CCCNC(=O)NCC1OC2CC(CC(=O)NCC3=NC=CN3C)OC2C1O,<rdkit.DataStructs.cDataStructs.ExplicitBitVec...,0.0,100664807.0,hek293,2328,"[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",1166,0,0
1,COCCNC(=O)NCC1OC2CC(CC(=O)NCC3=NC=CN3C)OC2C1O,<rdkit.DataStructs.cDataStructs.ExplicitBitVec...,0.0,100609055.0,hek293,7393,"[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, ...",519,0,0
3,CC1(O)CCC2(CCC(=O)NCCN3CCOCC3)C(NC(=O)C3=CC=CN...,<rdkit.DataStructs.cDataStructs.ExplicitBitVec...,0.0,25339573.0,hek293,1474,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",721,2,0

--- Checking HEK293_test_BM.pkl ---
Type: <class 'pandas.core.frame.DataFrame'>
Columns: ['SMILES', 'mol', 'Outcome', 'PUBCHEM_CID', 'cell_type', 'cluster_id', 'MorganFP', 'TB_Cluster', 'BM_Cluster', 'Fold']

,SMILES,mol,Outcome,PUBCHEM_CID,cell_type,cluster_id,MorganFP,TB_Cluster,BM_Cluster,Fold
3,CC1(O)CCC2(CCC(=O)NCCN3CCOCC3)C(NC(=O)C3=CC=CN...,<rdkit.DataStructs.cDataStructs.ExplicitBitVec...,0.0,25339573.0,hek293,1474,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",721,2,0
6,CC(=O)N1CCC(NC2CC(C)(C)C3CC(C)(O)CCC23CCC(=O)N...,<rdkit.DataStructs.cDataStructs.ExplicitBitVec...,0.0,28961163.0,hek293,8078,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",721,5,0
7,CC1=NOC(C)=C1CCC(=O)NC(C1=CN(C)N=C1)C1CC(O)C1,<rdkit.DataStructs.cDataStructs.ExplicitBitVec...,0.0,91763998.0,hek293,14070,"[0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",664,6,0

--- Checking tox21_all.pkl ---
Type: <class 'pandas.core.frame.DataFrame'>
Columns: ['SMILES', 'Outcome', 'dataset', 'MorganFP', 'TB_Cluster', 'BM_Cluster', 'TB_uniformity', 'BM_uniformity', 'Difficulty']

,SMILES,Outcome,dataset,MorganFP,TB_Cluster,BM_Cluster,TB_uniformity,BM_uniformity,Difficulty
36846,NS(=O)(=O)c1ccc(C(=O)O)cc1,0.0,tox21_df,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",452,5547,Heterogeneous,Heterogeneous,Hard
36847,OC(CCN1CCCCC1)(c1ccccc1)c1ccccc1,0.0,tox21_df,"[0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",1502,20471,Heterogeneous,Homogeneous,Ambiguous
36848,Oc1ccc(Cl)cc1Sc1cc(Cl)ccc1O,1.0,tox21_df,"[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",1148,20472,Homogeneous,Homogeneous,Easy

In [10]:
import pandas as pd
import pickle
import os

# --- SETUP ---
DATA_FOLDER = 'cytotoxicity_data'

file_pairs = [
    ('HEK293_train_BM.pkl', 'HEK293_train_BM_AC.pkl'),
    ('HEK293_test_BM.pkl',  'HEK293_test_BM_AC.pkl'),
    ('tox21_all.pkl',       'tox21_all_AC.pkl')
]

def load_pkl(file_name):
    with open(os.path.join(DATA_FOLDER, file_name), 'rb') as f:
        # Using latin1 to handle NumPy/Pandas cross-version compatibility
        return pickle.load(f, encoding='latin1')

# --- PROCESSING ---
for orig_name, ac_name in file_pairs:
    print(f"📦 Processing: {orig_name}")
    
    df_orig = load_pkl(orig_name)
    df_ac = load_pkl(ac_name)
    
    # Identify unique columns in the AC version
    new_cols = [c for c in df_ac.columns if c not in df_orig.columns]
    
    # 1. SPECIAL CASE: tox21 (Positional Alignment)
    if 'tox21' in orig_name:
        print("   🔗 Applying Positional Alignment (Row-by-Row)")
        # Since rows align perfectly, we can just join on the index
        # We take only the new columns from df_ac
        df_aca = pd.concat([df_orig, df_ac[new_cols]], axis=1)
        
    # 2. STANDARD CASE: HEK (CID Alignment)
    else:
        print("   🔗 Applying CID-based Alignment")
        # Find the CID column name (handling potential case differences)
        cid_col = next((c for c in df_orig.columns if 'pubchem' in str(c).lower()), 'PUBCHEM_CID')
        
        # Merge ensuring original order is preserved
        df_aca = pd.merge(
            df_orig, 
            df_ac[[cid_col] + new_cols], 
            on=cid_col, 
            how='left'
        )

    # --- SAVE RESULT ---
    aca_name = ac_name.replace('_AC.pkl', '_ACA.pkl')
    # Backup replace if naming varies
    if aca_name == ac_name:
        aca_name = ac_name.replace('.pkl', '_ACA.pkl')
        
    output_path = os.path.join(DATA_FOLDER, aca_name)
    
    with open(output_path, 'wb') as f:
        pickle.dump(df_aca, f)
    
    print(f"   ✨ Created: {aca_name}")
    print(f"   📊 Final Shape: {df_aca.shape}\n")

print("✅ All files aligned and saved successfully.")

📦 Processing: HEK293_train_BM.pkl
   🔗 Applying CID-based Alignment
   ✨ Created: HEK293_train_BM_ACA.pkl
   📊 Final Shape: (29342, 20)

📦 Processing: HEK293_test_BM.pkl
   🔗 Applying CID-based Alignment
   ✨ Created: HEK293_test_BM_ACA.pkl
   📊 Final Shape: (7253, 18)

📦 Processing: tox21_all.pkl
   🔗 Applying Positional Alignment (Row-by-Row)
   ✨ Created: tox21_all_ACA.pkl
   📊 Final Shape: (4958, 17)

✅ All files aligned and saved successfully.

In [12]:
import pandas as pd
import pickle
import os

DATA_FOLDER = 'cytotoxicity_data'
orig_name = 'tox21_all.pkl'
ac_name = 'tox21_all_AC.pkl'

def load_pkl(file_name):
    with open(os.path.join(DATA_FOLDER, file_name), 'rb') as f:
        return pickle.load(f, encoding='latin1')

# 1. LOAD
df_orig = load_pkl(orig_name)
df_ac = load_pkl(ac_name)

# 2. IDENTIFY SMILES COLUMN
s_col = next((c for c in df_orig.columns if 'smiles' in str(c).lower()), 'SMILES')

# 3. MANUAL ROW-BY-ROW CHECK AND SLICING
# We only take rows from df_ac that match the length of df_orig
# and verify alignment one last time
if len(df_orig) == len(df_ac):
    # Check if every single row matches at the exact same position
    matches = (df_orig[s_col].values == df_ac[s_col].values).all()
    
    if matches:
        print("✅ Alignment verified. Gluing columns now...")
        
        # Identify only the columns that are NOT in the original file
        new_cols = [c for c in df_ac.columns if c not in df_orig.columns]
        
        # Concatenate horizontally (axis=1) 
        # We reset the index to ensure they line up perfectly by row number
        df_aca = pd.concat([df_orig.reset_index(drop=True), 
                           df_ac[new_cols].reset_index(drop=True)], 
                          axis=1)
        
        print(f"✅ Success! New Row Count: {len(df_aca)} (Should be 2480)")
        
        # 4. SAVE
        aca_name = ac_name.replace('_AC.pkl', '_ACA.pkl')
        with open(os.path.join(DATA_FOLDER, aca_name), 'wb') as f:
            pickle.dump(df_aca, f)
            
    else:
        print("❌ SMILES do not match row-for-row. Manual glueing aborted.")
else:
    print(f"❌ Length mismatch: Orig({len(df_orig)}) vs AC({len(df_ac)})")

✅ Alignment verified. Gluing columns now...
✅ Success! New Row Count: 2479 (Should be 2480)

In [13]:
import pandas as pd
import pickle
import os

# --- SETUP ---
DATA_FOLDER = 'cytotoxicity_data'
# The files we just created
aca_files = [
    'HEK293_train_BM_ACA.pkl',
    'HEK293_test_BM_ACA.pkl',
    'tox21_all_ACA.pkl'
]

def check_aca_files(folder, files):
    for f_name in files:
        file_path = os.path.join(folder, f_name)
        
        if not os.path.exists(file_path):
            print(f"❌ File not found: {f_name}")
            continue
            
        with open(file_path, 'rb') as f:
            # Using latin1 to maintain the data stream integrity
            df = pickle.load(f, encoding='latin1')
        
        print(f"\n{'='*60}")
        print(f"📄 FILE: {f_name}")
        print(f"{'='*60}")
        print(f"📈 Total Rows: {len(df)}")
        print(f"📋 Total Columns: {len(df.columns)}")
        
        # Split columns for better readability
        # Identify the AC-specific columns vs the original ones
        ac_keywords = ['ac_', 'in_', 'is_', '_x', '_y', 'id', 'Dataset']
        new_cols = [c for c in df.columns if any(k in str(c) for k in ac_keywords)]
        orig_cols = [c for c in df.columns if c not in new_cols]
        
        print("\n🔹 Original Columns Preserved:")
        print(f"  {orig_cols}")
        
        print("\n🔸 New ACA Columns Added:")
        print(f"  {new_cols}")
        
        # Sanity check on the first row
        print("\n🔍 Row 0 SMILES Check:")
        s_col = next((c for c in df.columns if 'smiles' in str(c).lower()), None)
        if s_col:
            print(f"  {df.iloc[0][s_col]}")

# Execute the check
check_aca_files(DATA_FOLDER, aca_files)

============================================================
📄 FILE: HEK293_train_BM_ACA.pkl
============================================================
📈 Total Rows: 29342
📋 Total Columns: 20

🔹 Original Columns Preserved:
  ['SMILES', 'mol', 'Outcome', 'PUBCHEM_CID', 'cell_type', 'MorganFP', 'TB_Cluster', 'BM_Cluster', 'Fold']

🔸 New ACA Columns Added:
  ['cluster_id', 'Outcome_x', 'Outcome_y', 'Dataset', 'id', 'in_any_ac', 'in_within_ac', 'in_cross_ac', 'ac_label', 'in_mmp_network', 'is_ac']

🔍 Row 0 SMILES Check:
  CCCNC(=O)NCC1OC2CC(CC(=O)NCC3=NC=CN3C)OC2C1O

============================================================
📄 FILE: HEK293_test_BM_ACA.pkl
============================================================
📈 Total Rows: 7253
📋 Total Columns: 18

🔹 Original Columns Preserved:
  ['SMILES', 'mol', 'Outcome', 'PUBCHEM_CID', 'cell_type', 'MorganFP', 'TB_Cluster', 'BM_Cluster', 'Fold']

🔸 New ACA Columns Added:
  ['cluster_id', 'Dataset', 'id', 'in_any_ac', 'in_within_ac', 'in_cross_ac', 'ac_label', 'in_mmp_network', 'is_ac']

🔍 Row 0 SMILES Check:
  CC1(O)CCC2(CCC(=O)NCCN3CCOCC3)C(NC(=O)C3=CC=CN=C3)CC(C)(C)C2C1

============================================================
📄 FILE: tox21_all_ACA.pkl
============================================================
📈 Total Rows: 2479
📋 Total Columns: 17

🔹 Original Columns Preserved:
  ['SMILES', 'Outcome', 'dataset', 'MorganFP', 'TB_Cluster', 'BM_Cluster', 'TB_uniformity', 'BM_uniformity', 'Difficulty']

🔸 New ACA Columns Added:
  ['Dataset', 'id', 'in_any_ac', 'in_within_ac', 'in_cross_ac', 'ac_label', 'in_mmp_network', 'is_ac']

🔍 Row 0 SMILES Check:
  NS(=O)(=O)c1ccc(C(=O)O)cc1

In [2]:
def load_custom_tox_data(
    data_dir='cytotoxicity_data',
    save_dir='./save',
    featurizer='GraphConv',
    reload=False
):
    # Initialize featurizer if passed as a string
    if featurizer == 'GraphConv':
        feat = dc.feat.MolGraphConvFeaturizer()
    elif featurizer == 'ECFP':
        feat = dc.feat.CircularFingerprint(size=1024)
    else:
        feat = featurizer

    # Instantiate loader with No Splitter and No Transformers
    loader = _ToxPKLLoader(
        featurizer=feat,
        splitter=None,             # Explicitly signal data is already split
        transformer_generators=[], # No weight/label transformation
        tasks=['Outcome'],
        data_dir=data_dir,
        save_dir=save_dir
    )
    
    return loader.load_dataset('custom_tox_experiment', reload=reload)

In [14]:
import pandas as pd
import pickle
import os

# --- SETUP ---
DATA_FOLDER = 'cytotoxicity_data'
ACA_FILE = 'tox21_all_ACA.pkl'
FILE_PATH = os.path.join(DATA_FOLDER, ACA_FILE)

def analyze_ac_labels(file_path):
    if not os.path.exists(file_path):
        print(f"❌ File not found: {file_path}")
        return

    with open(file_path, 'rb') as f:
        df = pickle.load(f, encoding='latin1')

    # Ensure the column exists
    if 'ac_label' not in df.columns:
        print(f"❌ Column 'ac_label' not found in {ACA_FILE}")
        print(f"Available columns: {df.columns.tolist()}")
        return

    print(f"📊 Activity Cliff Statistics for {ACA_FILE}")
    print("=" * 50)

    # 1. Get raw counts of each unique value
    # value_counts() handles the frequency of each label
    label_stats = df['ac_label'].value_counts(dropna=False)

    # 2. Get percentages
    label_perc = df['ac_label'].value_counts(normalize=True, dropna=False) * 100

    # 3. Combine into a neat summary table
    summary = pd.DataFrame({
        'Count': label_stats,
        'Percentage (%)': label_perc.round(2)
    })

    print(summary)
    
    # 4. Specific Insights
    total_molecules = len(df)
    nan_count = df['ac_label'].isna().sum()
    
    print("-" * 50)
    print(f"Total Rows Analyzed: {total_molecules}")
    print(f"Molecules without labels (NaN): {nan_count}")

# Run the analysis
analyze_ac_labels(FILE_PATH)

📊 Activity Cliff Statistics for tox21_all_ACA.pkl
==================================================
                       Count  Percentage (%)
ac_label
AC                      1354           54.62
non-AC (no MMP match)    818           33.00
non-AC                   307           12.38
--------------------------------------------------
Total Rows Analyzed: 2479
Molecules without labels (NaN): 0

In [15]:
import os
import pandas as pd
import numpy as np
import deepchem as dc
from deepchem.molnet.load_function.molnet_loader import _MolnetLoader

class _ToxPKLLoader(_MolnetLoader):
    def create_dataset(self) -> dc.data.Dataset:
        pass

    def load_dataset(self, name: str, reload: bool = True):
        files = {'train': "HEK293_train_BM.pkl", 'val': "HEK293_test_BM.pkl", 'test': "tox21_all.pkl"}
        datasets = []

        for split, filename in files.items():
            path = os.path.join(self.data_dir, filename)
            if not os.path.exists(path):
                print(f"Skipping {split}: {path} not found.")
                continue
            
            df = pd.read_pickle(path)
            # Use ECFP featurizer passed from the call function
            features = self.featurizer.featurize(df['SMILES'].tolist())
            
            # Filter out failures (ECFP returns an empty array for failed SMILES)
            valid_inds = [i for i, f in enumerate(features) if f.size > 0]
            
            if len(valid_inds) == 0:
                print(f"Warning: No valid molecules in {split}")
                continue

            # ECFP features are typically (n_samples, n_bits)
            clean_features = np.stack([features[i] for i in valid_inds])
            clean_labels = df['Outcome'].values[valid_inds].reshape(-1, 1)
            clean_ids = np.array(df['SMILES'].tolist())[valid_inds]

            ds = dc.data.DiskDataset.from_numpy(X=clean_features, y=clean_labels, ids=clean_ids)
            datasets.append(ds)
            print(f"Loaded {split}: {len(ds)} samples.")

        return ['Outcome'], tuple(datasets), []

def load_custom_ecfp_tox(data_dir='cytotoxicity_data', size=1024):
    # Directly initialize the ECFP featurizer
    featurizer = dc.feat.CircularFingerprint(size=size, radius=2)
    
    loader = _ToxPKLLoader(
        featurizer=featurizer,
        splitter=None,
        transformer_generators=[],
        tasks=['Outcome'],
        data_dir=data_dir,
        save_dir='./save_ecfp'
    )
    return loader.load_dataset('custom_tox_ecfp', reload=False)

In [16]:
tasks, datasets, transformers = load_custom_ecfp_tox(data_dir='cytotoxicity_data')

if len(datasets) == 3:
    train, val, test = datasets
    print("-" * 30)
    print(f"Final Test - Train Size: {len(train)}")
    print(f"Final Test - Val Size:   {len(val)}")
    print(f"Final Test - Test Size:  {len(test)}")
    print(f"Feature Shape: {train.X.shape}") # Should be (N, 1024)
else:
    print("Error: Not all splits were loaded. Check your data_dir and file names.")

[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator
[10:05:54] DEPRECATION WARNING: please use MorganGenerator

Loaded train: 29342 samples.

[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator
[10:06:26] DEPRECATION WARNING: please use MorganGenerator

Loaded val: 7253 samples.

[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator
[10:06:34] DEPRECATION WARNING: please use MorganGenerator

Loaded test: 2479 samples.
------------------------------
Final Test - Train Size: 29342
Final Test - Val Size:   7253
Final Test - Test Size:  2479
Feature Shape: (29342, 1024)

In [1]:
import sys
import types
import numpy as np
import pandas as pd
import pickle
import os

# 1. ESTABLISH THE BRIDGE (Fixes NumPy 2.x compatibility)
_core = types.ModuleType("numpy._core")
_core.__path__ = [] 
sys.modules['numpy._core'] = _core
sys.modules['numpy._core.numeric'] = np.core.numeric
sys.modules['numpy._core.multiarray'] = np.core.multiarray
sys.modules['numpy._core.umath'] = np.core.umath

DATA_FOLDER = 'cytotoxicity_data'
files = ['HEK293_train_BM.pkl', 'HEK293_test_BM.pkl', 'tox21_all.pkl']
# The essential columns for the DeepChem pipeline
IMPORTANT_COLUMNS = ['SMILES', 'Outcome']

def pkl_to_csv_bridge(folder, file_name):
    file_path = os.path.join(folder, file_name)
    csv_path = file_path.replace(".pkl", ".csv")
    
    if not os.path.exists(file_path):
        print(f"Skipping: {file_name} not found.")
        return

    # 2. LOAD USING THE BRIDGE
    with open(file_path, 'rb') as f:
        # encoding='latin1' is critical for NumPy array reconstruction
        data = pickle.load(f, encoding='latin1')
    
    # 3. EXTRACT AND STORE
    if isinstance(data, pd.DataFrame):
        # Keep only SMILES and Outcome to ensure clean CSV storage
        df_to_save = data[IMPORTANT_COLUMNS]
        df_to_save.to_csv(csv_path, index=False)
        print(f"✅ Converted {file_name} -> {os.path.basename(csv_path)} ({len(df_to_save)} rows)")
    else:
        print(f"❌ Error: {file_name} did not load as a DataFrame.")

# Execute conversion
for f in files:
    pkl_to_csv_bridge(DATA_FOLDER, f)

✅ Converted HEK293_train_BM.pkl -> HEK293_train_BM.csv (29342 rows)
✅ Converted HEK293_test_BM.pkl -> HEK293_test_BM.csv (7253 rows)
✅ Converted tox21_all.pkl -> tox21_all.csv (2479 rows)

In [1]:
import pandas as pd
import numpy as np
import deepchem as dc
import os

def process_and_inspect_csv(file_path, featurizer_type='ECFP'):
    print(f"\n{'='*40}")
    print(f"Inspecting: {os.path.basename(file_path)}")
    print(f"{'='*40}")
    
    # 1. Load the "Clean" Data
    df = pd.read_csv(file_path)
    
    # 2. General Statistics (Native NumPy 2.0 types)
    total = len(df)
    actives = df['Outcome'].sum()
    inactives = total - actives
    ratio = inactives / actives if actives > 0 else 0
    
    print(f"Total Molecules: {total}")
    print(f"Class Distribution: {actives} Actives / {inactives} Inactives")
    print(f"Imbalance Ratio: 1 : {ratio:.2f}")

    # 3. Initialize Featurizer
    if featurizer_type == 'ECFP':
        featurizer = dc.feat.CircularFingerprint(size=1024, radius=2)
    else:
        featurizer = dc.feat.MolGraphConvFeaturizer()

    # 4. Featurize (This generates NumPy 2.0.0 native arrays)
    print(f"Featurizing with {featurizer_type}...")
    features = featurizer.featurize(df['SMILES'].tolist())
    
    # Filter out any failed SMILES
    valid_inds = [i for i, f in enumerate(features) if hasattr(f, 'size') and f.size > 0]
    
    X = np.array([features[i] for i in valid_inds])
    y = df['Outcome'].values[valid_inds].reshape(-1, 1)
    ids = df['SMILES'].values[valid_inds]

    # 5. Create DeepChem DiskDataset
    dataset = dc.data.DiskDataset.from_numpy(X=X, y=y, ids=ids)
    
    print(f"Final Dataset Shape: X={dataset.X.shape}, y={dataset.y.shape}")
    return dataset

# --- EXECUTION ---
DATA_FOLDER = 'cytotoxicity_data'
csv_files = ['HEK293_train_BM.csv', 'HEK293_test_BM.csv', 'tox21_all.csv']

processed_datasets = {}
for f in csv_files:
    full_path = os.path.join(DATA_FOLDER, f)
    if os.path.exists(full_path):
        split_name = f.split('.')[0]
        processed_datasets[split_name] = process_and_inspect_csv(full_path)

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 739, in start
    self.io_loop.start()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/tornado/platform/asyncio.py", line 211, in start
    self.asyncio_loop.run_forever()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 519, in dispatch_queue
    await self.process_one()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 508, in process_one
    await dispatch(*args)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 400, in dispatch_shell
    await result
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 368, in execute_request
    await super().execute_request(stream, ident, parent)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 455, in do_execute
    res = shell.run_cell(
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/zmqshell.py", line 602, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/IPython/core/async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/78/0hjzp4f53lq4mw5_d959f_p00000gn/T/ipykernel_16337/3174182999.py", line 3, in <module>
    import deepchem as dc
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/deepchem/__init__.py", line 8, in <module>
    import deepchem.data
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/deepchem/data/__init__.py", line 19, in <module>
    from deepchem.data.data_loader import DataLoader
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/deepchem/data/data_loader.py", line 16, in <module>
    from deepchem.feat import UserDefinedFeaturizer, Featurizer
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/deepchem/feat/__init__.py", line 24, in <module>
    from deepchem.feat.molecule_featurizers import AtomicCoordinates
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/deepchem/feat/molecule_featurizers/__init__.py", line 10, in <module>
    from deepchem.feat.molecule_featurizers.mol2vec_fingerprint import Mol2VecFingerprint
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/deepchem/feat/molecule_featurizers/mol2vec_fingerprint.py", line 5, in <module>
    from rdkit.Chem import AllChem
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/rdkit/__init__.py", line 23, in <module>
    from rdkit.Chem.Draw import IPythonConsole
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/rdkit/Chem/__init__.py", line 15, in <module>
    from rdkit import DataStructs, RDConfig, rdBase
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/rdkit/DataStructs/__init__.py", line 13, in <module>
    from rdkit.DataStructs import cDataStructs

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 739, in start
    self.io_loop.start()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/tornado/platform/asyncio.py", line 211, in start
    self.asyncio_loop.run_forever()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 519, in dispatch_queue
    await self.process_one()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 508, in process_one
    await dispatch(*args)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 400, in dispatch_shell
    await result
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 368, in execute_request
    await super().execute_request(stream, ident, parent)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 455, in do_execute
    res = shell.run_cell(
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/zmqshell.py", line 602, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/IPython/core/async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/78/0hjzp4f53lq4mw5_d959f_p00000gn/T/ipykernel_16337/3174182999.py", line 3, in <module>
    import deepchem as dc
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/deepchem/__init__.py", line 8, in <module>
    import deepchem.data
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/deepchem/data/__init__.py", line 19, in <module>
    from deepchem.data.data_loader import DataLoader
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/deepchem/data/data_loader.py", line 16, in <module>
    from deepchem.feat import UserDefinedFeaturizer, Featurizer
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/deepchem/feat/__init__.py", line 24, in <module>
    from deepchem.feat.molecule_featurizers import AtomicCoordinates
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/deepchem/feat/molecule_featurizers/__init__.py", line 10, in <module>
    from deepchem.feat.molecule_featurizers.mol2vec_fingerprint import Mol2VecFingerprint
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/deepchem/feat/molecule_featurizers/mol2vec_fingerprint.py", line 5, in <module>
    from rdkit.Chem import AllChem
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/rdkit/__init__.py", line 23, in <module>
    from rdkit.Chem.Draw import IPythonConsole
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/rdkit/Chem/__init__.py", line 16, in <module>
    from rdkit.Chem import rdchem

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 739, in start
    self.io_loop.start()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/tornado/platform/asyncio.py", line 211, in start
    self.asyncio_loop.run_forever()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 519, in dispatch_queue
    await self.process_one()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 508, in process_one
    await dispatch(*args)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 400, in dispatch_shell
    await result
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 368, in execute_request
    await super().execute_request(stream, ident, parent)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 455, in do_execute
    res = shell.run_cell(
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/zmqshell.py", line 602, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/IPython/core/async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/78/0hjzp4f53lq4mw5_d959f_p00000gn/T/ipykernel_16337/3174182999.py", line 3, in <module>
    import deepchem as dc
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/deepchem/__init__.py", line 8, in <module>
    import deepchem.data
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/deepchem/data/__init__.py", line 19, in <module>
    from deepchem.data.data_loader import DataLoader
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/deepchem/data/data_loader.py", line 16, in <module>
    from deepchem.feat import UserDefinedFeaturizer, Featurizer
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/deepchem/feat/__init__.py", line 24, in <module>
    from deepchem.feat.molecule_featurizers import AtomicCoordinates
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/deepchem/feat/molecule_featurizers/__init__.py", line 10, in <module>
    from deepchem.feat.molecule_featurizers.mol2vec_fingerprint import Mol2VecFingerprint
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/deepchem/feat/molecule_featurizers/mol2vec_fingerprint.py", line 5, in <module>
    from rdkit.Chem import AllChem
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/rdkit/__init__.py", line 23, in <module>
    from rdkit.Chem.Draw import IPythonConsole
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/rdkit/Chem/__init__.py", line 24, in <module>
    from rdkit.Chem.rdmolops import *

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 739, in start
    self.io_loop.start()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/tornado/platform/asyncio.py", line 211, in start
    self.asyncio_loop.run_forever()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 519, in dispatch_queue
    await self.process_one()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 508, in process_one
    await dispatch(*args)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 400, in dispatch_shell
    await result
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 368, in execute_request
    await super().execute_request(stream, ident, parent)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 455, in do_execute
    res = shell.run_cell(
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/zmqshell.py", line 602, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/IPython/core/async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/78/0hjzp4f53lq4mw5_d959f_p00000gn/T/ipykernel_16337/3174182999.py", line 3, in <module>
    import deepchem as dc
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/deepchem/__init__.py", line 8, in <module>
    import deepchem.data
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/deepchem/data/__init__.py", line 19, in <module>
    from deepchem.data.data_loader import DataLoader
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/deepchem/data/data_loader.py", line 16, in <module>
    from deepchem.feat import UserDefinedFeaturizer, Featurizer
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/deepchem/feat/__init__.py", line 24, in <module>
    from deepchem.feat.molecule_featurizers import AtomicCoordinates
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/deepchem/feat/molecule_featurizers/__init__.py", line 10, in <module>
    from deepchem.feat.molecule_featurizers.mol2vec_fingerprint import Mol2VecFingerprint
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/deepchem/feat/molecule_featurizers/mol2vec_fingerprint.py", line 5, in <module>
    from rdkit.Chem import AllChem
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/rdkit/__init__.py", line 23, in <module>
    from rdkit.Chem.Draw import IPythonConsole
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/rdkit/Chem/Draw/__init__.py", line 20, in <module>
    from rdkit.Chem import rdDepictor

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 739, in start
    self.io_loop.start()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/tornado/platform/asyncio.py", line 211, in start
    self.asyncio_loop.run_forever()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 519, in dispatch_queue
    await self.process_one()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 508, in process_one
    await dispatch(*args)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 400, in dispatch_shell
    await result
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 368, in execute_request
    await super().execute_request(stream, ident, parent)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 455, in do_execute
    res = shell.run_cell(
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/zmqshell.py", line 602, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/IPython/core/async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/78/0hjzp4f53lq4mw5_d959f_p00000gn/T/ipykernel_16337/3174182999.py", line 3, in <module>
    import deepchem as dc
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/deepchem/__init__.py", line 8, in <module>
    import deepchem.data
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/deepchem/data/__init__.py", line 19, in <module>
    from deepchem.data.data_loader import DataLoader
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/deepchem/data/data_loader.py", line 16, in <module>
    from deepchem.feat import UserDefinedFeaturizer, Featurizer
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/deepchem/feat/__init__.py", line 24, in <module>
    from deepchem.feat.molecule_featurizers import AtomicCoordinates
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/deepchem/feat/molecule_featurizers/__init__.py", line 10, in <module>
    from deepchem.feat.molecule_featurizers.mol2vec_fingerprint import Mol2VecFingerprint
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/deepchem/feat/molecule_featurizers/mol2vec_fingerprint.py", line 5, in <module>
    from rdkit.Chem import AllChem
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/rdkit/__init__.py", line 23, in <module>
    from rdkit.Chem.Draw import IPythonConsole
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/rdkit/Chem/Draw/__init__.py", line 21, in <module>
    from rdkit.Chem.Draw import rdMolDraw2D

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 739, in start
    self.io_loop.start()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/tornado/platform/asyncio.py", line 211, in start
    self.asyncio_loop.run_forever()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 519, in dispatch_queue
    await self.process_one()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 508, in process_one
    await dispatch(*args)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 400, in dispatch_shell
    await result
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 368, in execute_request
    await super().execute_request(stream, ident, parent)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 455, in do_execute
    res = shell.run_cell(
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/zmqshell.py", line 602, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/IPython/core/async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/78/0hjzp4f53lq4mw5_d959f_p00000gn/T/ipykernel_16337/3174182999.py", line 3, in <module>
    import deepchem as dc
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/deepchem/__init__.py", line 8, in <module>
    import deepchem.data
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/deepchem/data/__init__.py", line 19, in <module>
    from deepchem.data.data_loader import DataLoader
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/deepchem/data/data_loader.py", line 16, in <module>
    from deepchem.feat import UserDefinedFeaturizer, Featurizer
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/deepchem/feat/__init__.py", line 24, in <module>
    from deepchem.feat.molecule_featurizers import AtomicCoordinates
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/deepchem/feat/molecule_featurizers/__init__.py", line 10, in <module>
    from deepchem.feat.molecule_featurizers.mol2vec_fingerprint import Mol2VecFingerprint
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/deepchem/feat/molecule_featurizers/mol2vec_fingerprint.py", line 5, in <module>
    from rdkit.Chem import AllChem
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/rdkit/Chem/AllChem.py", line 22, in <module>
    from rdkit.Chem.EnumerateStereoisomers import (EnumerateStereoisomers,
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/rdkit/Chem/EnumerateStereoisomers.py", line 4, in <module>
    from rdkit.Chem.rdDistGeom import EmbedMolecule

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 739, in start
    self.io_loop.start()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/tornado/platform/asyncio.py", line 211, in start
    self.asyncio_loop.run_forever()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 519, in dispatch_queue
    await self.process_one()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 508, in process_one
    await dispatch(*args)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 400, in dispatch_shell
    await result
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 368, in execute_request
    await super().execute_request(stream, ident, parent)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 455, in do_execute
    res = shell.run_cell(
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/zmqshell.py", line 602, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/IPython/core/async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/78/0hjzp4f53lq4mw5_d959f_p00000gn/T/ipykernel_16337/3174182999.py", line 3, in <module>
    import deepchem as dc
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/deepchem/__init__.py", line 8, in <module>
    import deepchem.data
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/deepchem/data/__init__.py", line 19, in <module>
    from deepchem.data.data_loader import DataLoader
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/deepchem/data/data_loader.py", line 16, in <module>
    from deepchem.feat import UserDefinedFeaturizer, Featurizer
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/deepchem/feat/__init__.py", line 24, in <module>
    from deepchem.feat.molecule_featurizers import AtomicCoordinates
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/deepchem/feat/molecule_featurizers/__init__.py", line 10, in <module>
    from deepchem.feat.molecule_featurizers.mol2vec_fingerprint import Mol2VecFingerprint
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/deepchem/feat/molecule_featurizers/mol2vec_fingerprint.py", line 5, in <module>
    from rdkit.Chem import AllChem
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/rdkit/Chem/AllChem.py", line 27, in <module>
    from rdkit.Chem.rdFingerprintGenerator import *

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 739, in start
    self.io_loop.start()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/tornado/platform/asyncio.py", line 211, in start
    self.asyncio_loop.run_forever()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 519, in dispatch_queue
    await self.process_one()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 508, in process_one
    await dispatch(*args)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 400, in dispatch_shell
    await result
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 368, in execute_request
    await super().execute_request(stream, ident, parent)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 455, in do_execute
    res = shell.run_cell(
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/zmqshell.py", line 602, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/IPython/core/async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/78/0hjzp4f53lq4mw5_d959f_p00000gn/T/ipykernel_16337/3174182999.py", line 3, in <module>
    import deepchem as dc
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/deepchem/__init__.py", line 8, in <module>
    import deepchem.data
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/deepchem/data/__init__.py", line 19, in <module>
    from deepchem.data.data_loader import DataLoader
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/deepchem/data/data_loader.py", line 16, in <module>
    from deepchem.feat import UserDefinedFeaturizer, Featurizer
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/deepchem/feat/__init__.py", line 24, in <module>
    from deepchem.feat.molecule_featurizers import AtomicCoordinates
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/deepchem/feat/molecule_featurizers/__init__.py", line 10, in <module>
    from deepchem.feat.molecule_featurizers.mol2vec_fingerprint import Mol2VecFingerprint
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/deepchem/feat/molecule_featurizers/mol2vec_fingerprint.py", line 5, in <module>
    from rdkit.Chem import AllChem
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/rdkit/Chem/AllChem.py", line 29, in <module>
    from rdkit.Chem.rdMolAlign import *

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 739, in start
    self.io_loop.start()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/tornado/platform/asyncio.py", line 211, in start
    self.asyncio_loop.run_forever()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 519, in dispatch_queue
    await self.process_one()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 508, in process_one
    await dispatch(*args)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 400, in dispatch_shell
    await result
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 368, in execute_request
    await super().execute_request(stream, ident, parent)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 455, in do_execute
    res = shell.run_cell(
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/zmqshell.py", line 602, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/IPython/core/async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/78/0hjzp4f53lq4mw5_d959f_p00000gn/T/ipykernel_16337/3174182999.py", line 3, in <module>
    import deepchem as dc
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/deepchem/__init__.py", line 8, in <module>
    import deepchem.data
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/deepchem/data/__init__.py", line 19, in <module>
    from deepchem.data.data_loader import DataLoader
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/deepchem/data/data_loader.py", line 16, in <module>
    from deepchem.feat import UserDefinedFeaturizer, Featurizer
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/deepchem/feat/__init__.py", line 24, in <module>
    from deepchem.feat.molecule_featurizers import AtomicCoordinates
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/deepchem/feat/molecule_featurizers/__init__.py", line 10, in <module>
    from deepchem.feat.molecule_featurizers.mol2vec_fingerprint import Mol2VecFingerprint
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/deepchem/feat/molecule_featurizers/mol2vec_fingerprint.py", line 5, in <module>
    from rdkit.Chem import AllChem
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/rdkit/Chem/AllChem.py", line 32, in <module>
    from rdkit.Chem.rdMolTransforms import *

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 739, in start
    self.io_loop.start()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/tornado/platform/asyncio.py", line 211, in start
    self.asyncio_loop.run_forever()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 519, in dispatch_queue
    await self.process_one()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 508, in process_one
    await dispatch(*args)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 400, in dispatch_shell
    await result
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 368, in execute_request
    await super().execute_request(stream, ident, parent)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 455, in do_execute
    res = shell.run_cell(
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/zmqshell.py", line 602, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/IPython/core/async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/78/0hjzp4f53lq4mw5_d959f_p00000gn/T/ipykernel_16337/3174182999.py", line 3, in <module>
    import deepchem as dc
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/deepchem/__init__.py", line 8, in <module>
    import deepchem.data
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/deepchem/data/__init__.py", line 19, in <module>
    from deepchem.data.data_loader import DataLoader
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/deepchem/data/data_loader.py", line 16, in <module>
    from deepchem.feat import UserDefinedFeaturizer, Featurizer
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/deepchem/feat/__init__.py", line 24, in <module>
    from deepchem.feat.molecule_featurizers import AtomicCoordinates
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/deepchem/feat/molecule_featurizers/__init__.py", line 10, in <module>
    from deepchem.feat.molecule_featurizers.mol2vec_fingerprint import Mol2VecFingerprint
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/deepchem/feat/molecule_featurizers/mol2vec_fingerprint.py", line 5, in <module>
    from rdkit.Chem import AllChem
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/rdkit/Chem/AllChem.py", line 35, in <module>
    from rdkit.Chem.rdReducedGraphs import *

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 739, in start
    self.io_loop.start()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/tornado/platform/asyncio.py", line 211, in start
    self.asyncio_loop.run_forever()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 519, in dispatch_queue
    await self.process_one()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 508, in process_one
    await dispatch(*args)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 400, in dispatch_shell
    await result
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 368, in execute_request
    await super().execute_request(stream, ident, parent)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 455, in do_execute
    res = shell.run_cell(
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/zmqshell.py", line 602, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/IPython/core/async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/78/0hjzp4f53lq4mw5_d959f_p00000gn/T/ipykernel_16337/3174182999.py", line 3, in <module>
    import deepchem as dc
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/deepchem/__init__.py", line 8, in <module>
    import deepchem.data
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/deepchem/data/__init__.py", line 19, in <module>
    from deepchem.data.data_loader import DataLoader
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/deepchem/data/data_loader.py", line 16, in <module>
    from deepchem.feat import UserDefinedFeaturizer, Featurizer
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/deepchem/feat/__init__.py", line 24, in <module>
    from deepchem.feat.molecule_featurizers import AtomicCoordinates
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/deepchem/feat/molecule_featurizers/__init__.py", line 10, in <module>
    from deepchem.feat.molecule_featurizers.mol2vec_fingerprint import Mol2VecFingerprint
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/deepchem/feat/molecule_featurizers/mol2vec_fingerprint.py", line 5, in <module>
    from rdkit.Chem import AllChem
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/rdkit/Chem/AllChem.py", line 36, in <module>
    from rdkit.Chem.rdShapeHelpers import *

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 739, in start
    self.io_loop.start()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/tornado/platform/asyncio.py", line 211, in start
    self.asyncio_loop.run_forever()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 519, in dispatch_queue
    await self.process_one()
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 508, in process_one
    await dispatch(*args)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 400, in dispatch_shell
    await result
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 368, in execute_request
    await super().execute_request(stream, ident, parent)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 455, in do_execute
    res = shell.run_cell(
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/ipykernel/zmqshell.py", line 602, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/IPython/core/async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/78/0hjzp4f53lq4mw5_d959f_p00000gn/T/ipykernel_16337/3174182999.py", line 3, in <module>
    import deepchem as dc
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/deepchem/__init__.py", line 8, in <module>
    import deepchem.data
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/deepchem/data/__init__.py", line 19, in <module>
    from deepchem.data.data_loader import DataLoader
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/deepchem/data/data_loader.py", line 16, in <module>
    from deepchem.feat import UserDefinedFeaturizer, Featurizer
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/deepchem/feat/__init__.py", line 24, in <module>
    from deepchem.feat.molecule_featurizers import AtomicCoordinates
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/deepchem/feat/molecule_featurizers/__init__.py", line 22, in <module>
    from deepchem.feat.molecule_featurizers.dmpnn_featurizer import DMPNNFeaturizer
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/deepchem/feat/molecule_featurizers/dmpnn_featurizer.py", line 24, in <module>
    class GraphConvConstants(object):
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/deepchem/feat/molecule_featurizers/dmpnn_featurizer.py", line 57, in GraphConvConstants
    RDKitDescriptors(use_bcut2d=False),
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/deepchem/feat/molecule_featurizers/rdkit_descriptors.py", line 87, in __init__
    from rdkit.Chem import Descriptors
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/rdkit/Chem/Descriptors.py", line 238, in <module>
    _setupDescriptors(locals())
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/rdkit/Chem/Descriptors.py", line 33, in _setupDescriptors
    from rdkit.Chem import (Crippen, Descriptors3D, Fragments, GraphDescriptors,
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/rdkit/Chem/GraphDescriptors.py", line 23, in <module>
    from rdkit.ML.InfoTheory import entropy
  File "/Users/tingyangwei/miniconda3/envs/uq/lib/python3.10/site-packages/rdkit/ML/InfoTheory/__init__.py", line 4, in <module>
    from rdkit.ML.InfoTheory.rdInfoTheory import *

AttributeError: _ARRAY_API not found

No normalization for SPS. Feature removed!
No normalization for AvgIpc. Feature removed!
Skipped loading some Tensorflow models, missing a dependency. No module named 'tensorflow'
Skipped loading modules with pytorch-geometric dependency, missing a dependency. No module named 'dgl'
Skipped loading modules with pytorch-lightning dependency, missing a dependency. No module named 'lightning'
Skipped loading some Jax models, missing a dependency. No module named 'jax'
Skipped loading some PyTorch models, missing a dependency. No module named 'tensorflow'
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator

========================================
Inspecting: HEK293_train_BM.csv
========================================
Total Molecules: 29342
Class Distribution: 4931.0 Actives / 24411.0 Inactives
Imbalance Ratio: 1 : 4.95
Featurizing with ECFP...

[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:13] DEPRECATION WARNING: please use MorganGenerator
[10:50:14] DEPRECATION WARNING: please use MorganGenerator
[10:50:14] DEPRECATION WARNING: please use MorganGenerator
[10:50:14] DEPRECATION WARNING: please use MorganGenerator
[10:50:14] DEPRECATION WARNING: please use MorganGenerator
[10:50:14] DEPRECATION WARNING: please use MorganGenerator
[10:50:14] DEPRECATION WARNING: please use MorganGenerator
[10:50:14] DEPRECATION WARNING: please use MorganGenerator
[10:50:14] DEPRECATION WARNING: please use MorganGenerator
[10:50:14] DEPRECATION WARNING: please use MorganGenerator
[10:50:14] DEPRECATION WARNING: please use MorganGenerator
[10:50:14] DEPRECATION WARNING: please use MorganGenerator
[10:50:14] DEPRECATION WARNING: please use MorganGenerator
[10:50:14] DEPRECATION WARNING: please use MorganGenerator
[10:50:14] DEPRECATION WARNING: please use MorganGenerator
[10:50:14] DEPRECATION WARNING: please use MorganGenerator
[10:50:14] DEPRECATION WARNING: please use MorganGenerator
[10:50:14] DEPRECATION WARNING: please use MorganGenerator
[10:50:14] DEPRECATION WARNING: please use MorganGenerator
[10:50:14] DEPRECATION WARNING: please use MorganGenerator
[10:50:14] DEPRECATION WARNING: please use MorganGenerator
[10:50:14] DEPRECATION WARNING: please use MorganGenerator
[10:50:14] DEPRECATION WARNING: please use MorganGenerator
[10:50:14] DEPRECATION WARNING: please use MorganGenerator
[10:50:14] DEPRECATION WARNING: please use MorganGenerator
[10:50:14] DEPRECATION WARNING: please use MorganGenerator
[10:50:14] DEPRECATION WARNING: please use MorganGenerator
[10:50:14] DEPRECATION WARNING: please use MorganGenerator
[10:50:14] DEPRECATION WARNING: please use MorganGenerator
[10:50:14] DEPRECATION WARNING: please use MorganGenerator
[10:50:14] DEPRECATION WARNING: please use MorganGenerator
[10:50:14] DEPRECATION WARNING: please use MorganGenerator
[10:50:14] DEPRECATION WARNING: please use MorganGenerator
[10:50:14] DEPRECATION WARNING: please use MorganGenerator
[10:50:14] DEPRECATION WARNING: please use MorganGenerator

Final Dataset Shape: X=(29342, 1024), y=(29342, 1)

========================================
Inspecting: HEK293_test_BM.csv
========================================
Total Molecules: 7253
Class Distribution: 1203.0 Actives / 6050.0 Inactives
Imbalance Ratio: 1 : 5.03
Featurizing with ECFP...

[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:31] DEPRECATION WARNING: please use MorganGenerator
[10:51:32] DEPRECATION WARNING: please use MorganGenerator
[10:51:32] DEPRECATION WARNING: please use MorganGenerator
[10:51:32] DEPRECATION WARNING: please use MorganGenerator
[10:51:32] DEPRECATION WARNING: please use MorganGenerator
[10:51:32] DEPRECATION WARNING: please use MorganGenerator

Final Dataset Shape: X=(7253, 1024), y=(7253, 1)

========================================
Inspecting: tox21_all.csv
========================================
Total Molecules: 2479
Class Distribution: 822.0 Actives / 1657.0 Inactives
Imbalance Ratio: 1 : 2.02
Featurizing with ECFP...

[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:49] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator
[10:51:50] DEPRECATION WARNING: please use MorganGenerator

Final Dataset Shape: X=(2479, 1024), y=(2479, 1)

[10:51:55] DEPRECATION WARNING: please use MorganGenerator
[10:51:55] DEPRECATION WARNING: please use MorganGenerator
[10:51:55] DEPRECATION WARNING: please use MorganGenerator
[10:51:55] DEPRECATION WARNING: please use MorganGenerator
[10:51:55] DEPRECATION WARNING: please use MorganGenerator
[10:51:55] DEPRECATION WARNING: please use MorganGenerator
[10:51:55] DEPRECATION WARNING: please use MorganGenerator
[10:51:55] DEPRECATION WARNING: please use MorganGenerator
[10:51:55] DEPRECATION WARNING: please use MorganGenerator
[10:51:55] DEPRECATION WARNING: please use MorganGenerator
[10:51:55] DEPRECATION WARNING: please use MorganGenerator
[10:51:55] DEPRECATION WARNING: please use MorganGenerator
[10:51:55] DEPRECATION WARNING: please use MorganGenerator
[10:51:55] DEPRECATION WARNING: please use MorganGenerator
[10:51:55] DEPRECATION WARNING: please use MorganGenerator
[10:51:55] DEPRECATION WARNING: please use MorganGenerator
[10:51:55] DEPRECATION WARNING: please use MorganGenerator
[10:51:55] DEPRECATION WARNING: please use MorganGenerator
[10:51:55] DEPRECATION WARNING: please use MorganGenerator
[10:51:55] DEPRECATION WARNING: please use MorganGenerator
[10:51:55] DEPRECATION WARNING: please use MorganGenerator
[10:51:55] DEPRECATION WARNING: please use MorganGenerator
[10:51:55] DEPRECATION WARNING: please use MorganGenerator
[10:51:55] DEPRECATION WARNING: please use MorganGenerator
[10:51:55] DEPRECATION WARNING: please use MorganGenerator
[10:51:55] DEPRECATION WARNING: please use MorganGenerator
[10:51:55] DEPRECATION WARNING: please use MorganGenerator
[10:51:55] DEPRECATION WARNING: please use MorganGenerator
[10:51:55] DEPRECATION WARNING: please use MorganGenerator
[10:51:55] DEPRECATION WARNING: please use MorganGenerator
[10:51:55] DEPRECATION WARNING: please use MorganGenerator
[10:51:55] DEPRECATION WARNING: please use MorganGenerator
[10:51:55] DEPRECATION WARNING: please use MorganGenerator
[10:51:55] DEPRECATION WARNING: please use MorganGenerator
[10:51:55] DEPRECATION WARNING: please use MorganGenerator
[10:51:55] DEPRECATION WARNING: please use MorganGenerator
[10:51:55] DEPRECATION WARNING: please use MorganGenerator
[10:51:55] DEPRECATION WARNING: please use MorganGenerator
[10:51:55] DEPRECATION WARNING: please use MorganGenerator
[10:51:55] DEPRECATION WARNING: please use MorganGenerator
[10:51:55] DEPRECATION WARNING: please use MorganGenerator
[10:51:55] DEPRECATION WARNING: please use MorganGenerator
[10:51:55] DEPRECATION WARNING: please use MorganGenerator
[10:51:55] DEPRECATION WARNING: please use MorganGenerator
[10:51:55] DEPRECATION WARNING: please use MorganGenerator
[10:51:55] DEPRECATION WARNING: please use MorganGenerator
[10:51:55] DEPRECATION WARNING: please use MorganGenerator
[10:51:55] DEPRECATION WARNING: please use MorganGenerator
[10:51:55] DEPRECATION WARNING: please use MorganGenerator

In [1]:
import pandas as pd
import os

# Configuration
DATA_FOLDER = 'cytotoxicity_data'
FILES = ['HEK293_train_BM.pkl', 'HEK293_test_BM.pkl', 'tox21_all.pkl']
IMPORTANT_COLUMNS = ['SMILES', 'Outcome']

def convert_to_csv(folder, file_name):
    file_path = os.path.join(folder, file_name)
    csv_path = file_path.replace(".pkl", ".csv")
    
    if not os.path.exists(file_path):
        print(f"File not found: {file_path}")
        return

    # Direct load: This will raise an error if NumPy versions/paths mismatch
    df = pd.read_pickle(file_path)
    
    # Select essential columns
    df_clean = df[IMPORTANT_COLUMNS]
    
    # Save as CSV
    df_clean.to_csv(csv_path, index=False)
    print(f"Successfully converted: {file_name} -> {os.path.basename(csv_path)}")

# Run conversion
for f in FILES:
    convert_to_csv(DATA_FOLDER, f)

Successfully converted: HEK293_train_BM.pkl -> HEK293_train_BM.csv
Successfully converted: HEK293_test_BM.pkl -> HEK293_test_BM.csv
Successfully converted: tox21_all.pkl -> tox21_all.csv